### PR TITLE
Added portal run id beside filenames

### PR DESCRIPTION
**Pull request by raylrui**
Draft to add portal run id in the analysis result for #324 
image

### CODE REVIEW

**Comment by victorskl** [comment]
So far looking good. Could add a link in "Portal Run Id" part; click to open in new browser to its documentation, pls.

https://github.com/umccr/data-portal-apis/blob/dev/docs/pipeline/portal_run_id.md

**Comment by victorskl** [comment]
Perhaps, could try it as a column? Instead of inline under. And, making the portal_run_id value to be copyable would be very helpful to user.

**Comment by raylrui** [comment]
Sure @victorskl can I assume it should look like this?

image

I thought it is kind of 'helper' information, so put it under main file name.

**Comment by victorskl** [comment]
Yup. That looks better. 

Eh, it is sort of important info for a file that user need to rely upon. 

Thanks Ray.

**Review by victorskl — APPROVED** [review]
LGTM 👍

**Pull request merged**
