### PR TITLE
feat: Oncoanalyser Trigger

### PR DESCRIPTION
**Pull request by williamputraintan**
- Implement Oncoanalyser trigger via lambda invoke
- Some refactor on metadata tables that could used across launch-pad pages

### CODE REVIEW

**Comment by williamputraintan** [comment]
[Portal Release - Ocicat: Implement Portal automation integration for oncoanalyser](https://trello.com/c/sZFv7FhZ/1488-portal-release-ocicat-implement-portal-automation-integration-for-oncoanalyser)

**Comment by victorskl** [comment]
Sorry for delay, Will. Reviewing now...

**Review by victorskl — APPROVED** [review]
LGTM for first pass, Will! I have a bit of feedback on UI component and improvement on UX flow. But that is not blocking this PR. So, please go ahead and merge.

Let us follow up tomorrow and, I will explain a bit more. All good.!

**Comment by williamputraintan** [comment]
Sure, merging ...

**Pull request merged**
