### PR TITLE
Release 2.2.4

### PR DESCRIPTION
**Pull request by victorskl**
Tested on dev. Looking good. Shipping to prod.

Summary changes:

- See related backend release PR
- https://github.com/umccr/data-portal-apis/pull/733

### CODE REVIEW

**Review by raylrui — APPROVED** [review]

**Comment by victorskl** [comment]
@williamputraintan When you are able, could you have a quick skim through, pls..

**Review by williamputraintan — APPROVED** [review]

**Comment by williamputraintan** [comment]
> @williamputraintan When you are able, could you have a quick skim through, pls..

Sorry approved!

**Comment by victorskl** [comment]
All good, busy days...

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
