### PR TITLE
Fix: Filter && Amplify Multi Param Query Behaviour 

### LINKED ISSUE #323: Broken Metadata Table in T/N Workflow Launch Pad
Query parameter is broken when querying data for the metadata-table. Perhaps this due to amplify update the behaviour of having the same query with multiple value

### PR DESCRIPTION
**Pull request by williamputraintan**
Fixing the filtering problem on lims page, which apparently is also related to the mutl-query params behaviour. 

Fix #323 , #322

### CODE REVIEW

**Comment by williamputraintan** [comment]
I think amplify change its implementation on API Config props

```
{
	queryParams: {"foo": ["bar1", "bar2"]}
}

```

Before the bug discovered it resolves to this

`...?foo=bar1&foo=bar2`

But now:

`...?foo=bar1,bar2`

So added some manual implementation to enforce what portal recognise (the first example).

**Comment by victorskl** [comment]
I will review this by later evening, today. ETA

**Review by victorskl — APPROVED** [review]
LGTM

**Review by raylrui — APPROVED** [review]
LGTM, test work as expected

**Comment by victorskl** [comment]
Yup, let merge this.

**Pull request merged**
